config_version: 0.0.1
globals:
  profile: m3c
  config_file: local_options.config
workflows:
- id: n01
  name: nf-core/fetchngs
  version: dev
  params:
    input: fetchngs-ids.csv
    outdir: out_fetchngs
    nf_core_pipeline: rnaseq
    nf_core_rnaseq_strandedness: auto
- id: n02
  name: nf-core/rnaseq
  version: dev
  params:
    input: ${n01:params:outdir}/samplesheet/samplesheet.csv
    genome: EB1
    outdir: out_rnaseq
- id: n03
  name: nf-core/differentialabundance
  version: dev
  profile: m3c,rnaseq
  params: 
    input: ${n01:params:outdir}/samplesheet/samplesheet.csv
    matrix: ${n02:params:outdir}/star_salmon/salmon.merged.gene_counts.tsv
    transcript_length_matrix: ${n02:params:outdir}/star_salmon/salmon.merged.gene_lengths.tsv
    outdir: out_diffab
transitions:
- id: e2
  target: n02
  source: n01
- id: e3
  target: n03
  source: n02
